name: my first workflow
on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout repo
            uses: actions/checkout@v4
            
          - name: Welcome Message
            run: |
                 echo "Welcome Praveen"
                 ls -ltra
                 cat test.txt

          - name: Generate ASCII Content
            run: cowsay -f dragon "Run for Cover, Darcarys..." >> dragon.txt            
    
          # - name: List files
          #   run:  ls

          # - name: Read file
          #   run: cat test.txt
            