name: my second workflow - Generate ASCII
on: push

jobs: 
    build_job: 
        runs-on: ubuntu-latest
        steps: 
          - name: Install Cowsay Package
            run: sudo apt-get install cowsay -y

          - name: Execute Cowsay CMD
            run: cowsay -f dragon "Run for Cover, Darcarys..." >> dragon.txt 

          - name: Upload file
            uses: actions/upload-artifact@v3
            with:
              name: dragon-artifact-file
              path: dragon.txt
          
          - name: Sleep for 10 seconds
            run: sleep 10

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
          - name: sleep for 5 seconds
            run: sleep 5

          - name: Download file
            uses: actions/download-artifact@v3
            with:
              name: dragon-artifact-file

          - name: Test for file exists
            run: grep -i "Darcarys" dragon.txt

    deploy_job:
        needs: [build_job, test_job]
        runs-on: ubuntu-latest
        steps:
          - name: Download file
            uses: actions/download-artifact@v3
            with:
              name: dragon-artifact-file

          - name: Reading file
            run: cat dragon.txt

          - name: Deployment
            run: echo Deploying....





