name: my second workflow - Generate ASCII
on: push

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout repo
            uses: actions/checkout@v4
            
          - name: Install Cowsay program
            run: sudo apt-get install cowsay -y          

          - name: Generate ASCII Content
            run: cowsay -f dragon "Run for Cover, Darcarys..." >> dragon.txt   

          - name: Test for file
            run: grep -i "Darcarys" dragon.txt

          - name: Read file
            run: cat dragon.txt

          - name: list repo files
            run: ls -ltra


